# Site
name: "ddoni's blog"
title: "ddoni's blog"
description: "connecting the dots"
logo: "https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1575058476/noticon/b7vmbdgm9krhkd6ejtjv.svg"
favicon: "https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1575058476/noticon/b7vmbdgm9krhkd6ejtjv.svg"
baseurl: ""
google_analytics: "UA-xxxxxxxx-1"
disqus: "demowebsite"
mailchimp-list: ""
include: ["_pages"]
permalink: /:title/
email: minn602@gmail.com

# Authors
authors:
  Minsun:
    name: Minsun
    display_name: Minsun
    avatar: "assets/images/cindy.png"
    email: minn602@gmail.com
    github: https://github.com/minn602
    description: "생산적이고 지속가능한 삶을 추구하는 프론트엔드 개발자입니다✨"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
